# –û–ø–∏—Å–∞–Ω–∏–µ:
# –í–µ–±-–∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å –¥–æ—Å—Ç—É–ø–µ–Ω –ø–æ –∞–¥—Ä–µ—Å—É http://192.168.1.1:9090/ui (–≤–º–µ—Å—Ç–æ 192.168.1.1 –º–æ–∂–µ—Ç –±—ã—Ç—å –ª—é–±–æ–π IP, –≥–¥–µ –∑–∞–ø—É—â–µ–Ω –¥–∞–Ω–Ω—ã–π –∫–æ–Ω—Ñ–∏–≥). –ü–æ—Å–ª–µ –¥–æ–±–∞–≤–ª–µ–Ω–∏—è —Å–µ—Ä–≤–µ—Ä–∞ –∏ –∑–∞–ø—É—Å–∫–∞ mihomo –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –∑–∞–π—Ç–∏ –≤ –≤–µ–±-–∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å –∏ –≤—ã–±—Ä–∞—Ç—å –Ω—É–∂–Ω–æ–µ –ø–æ–¥–∫–ª—é—á–µ–Ω–∏–µ –¥–ª—è –ø—Ä–æ–∫—Å–∏-–≥—Ä—É–ø–ø
# –ì—Ä—É–ø–ø–∞ "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã" —Å–æ–¥–µ—Ä–∂–∏—Ç —Å–ø–∏—Å–æ–∫ –¥–æ–º–µ–Ω–æ–≤ –±–æ–ª—å—à–∏–Ω—Å—Ç–≤–∞ –∑–∞–±–ª–æ–∫–∏—Ä–æ–≤–∞–Ω–Ω—ã—Ö —Ä–µ—Å—É—Ä—Å–æ–≤ (–∫–∞–∫ —Å–Ω–∞—Ä—É–∂–∏, —Ç–∞–∫ –∏ –≤–Ω—É—Ç—Ä–∏)
# –û—Å—Ç–∞–ª—å–Ω—ã–µ –≥—Ä—É–ø–ø—ã YouTube/Discord –∏ —Ç–¥ –∏–º–µ—é—Ç –ø—Ä–∏–æ—Ä–∏—Ç–µ—Ç –Ω–∞–¥ –≥—Ä—É–ø–ø–æ–π "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã". E—Å–ª–∏ –ø–µ—Ä–µ–æ–ø—Ä–µ–¥–µ–ª–µ–Ω–∏–µ –Ω–µ –Ω—É–∂–Ω–æ, –º–æ–∂–Ω–æ –≤—ã–±—Ä–∞—Ç—å "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã" –≤ –∫–∞—á–µ—Å—Ç–≤–µ –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è –∏ —É–ø—Ä–∞–≤–ª—è—Ç—å –≤—Å–µ–º–∏ –≥—Ä—É–ø–ø–∞–º–∏ —Ä–∞–∑–æ–º –≤ –≥—Ä—É–ø–ø–µ "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã"
# –ü—Ä–∏ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–∏ —Å XKeen —Ä–µ–∫–æ–º–µ–Ω–¥—É–µ—Ç—Å—è –≤—ã–ø–æ–ª–Ω–∏—Ç—å –∫–æ–º–∞–Ω–¥—É "xkeen -ap 80,443,2000:2300,8443,19200:19400,50000:50030" –≤ SSH —Ç–µ—Ä–º–∏–Ω–∞–ª–µ —Ä–æ—É—Ç–µ—Ä–∞

log-level: silent
allow-lan: true
tproxy-port: 5000
ipv6: true
mode: rule
external-controller: 0.0.0.0:9090
external-ui: zashboard
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
profile: { store-selected: true }

sniffer:
  enable: true
  sniff:
    HTTP:
    TLS:
    QUIC:

proxy-groups:
  - name: –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Reject.png
    include-all: true

  - name: YouTube
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Discord
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Twitch
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    include-all: true
    proxies: [DIRECT, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Reddit
    type: select
    icon: https://www.redditstatic.com/shreddit/assets/favicon/192x192.png
    include-all: true
    proxies: [DIRECT, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Meta
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/meta.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Spotify
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    include-all: true
    exclude-filter: üá∑üá∫
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Telegram
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    include-all: true
    proxies: [DIRECT, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Steam
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    include-all: true
    proxies: [DIRECT, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Cloudflare
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    include-all: true
    proxies: [PASS, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: AI
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    include-all: true
    exclude-filter: üá∑üá∫
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Twitter
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: QUIC
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/quic.png
    proxies: [REJECT, PASS]

#–ü—Ä–∏–º–µ—Ä –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è —Å –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ–º –ø–æ–¥–ø–∏—Å–∫–∏ (–£–î–ê–õ–ò–¢–¨, –ï–°–õ–ò –ù–ï –ù–£–ñ–ï–ù!)
proxy-providers:
  proxy-sub:
    type: http
    url: *subscription.link*
    path: ./proxy-providers/proxy-sub.yml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 2000
      lazy: false
      expected-status: 204
    override:
      udp: true
      tfo: true

#–ü—Ä–∏–º–µ—Ä vless –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è –±–µ–∑ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è –ø–æ–¥–ø–∏—Å–∫–∏ (–£–î–ê–õ–ò–¢–¨, –ï–°–õ–ò –ù–ï –ù–£–ñ–ï–ù!)
proxies:
  - name: vless-reality
    type: vless
    server: *your-server*
    port: 443
    network: tcp
    udp: true
    tls: true
    servername: *your-sni*
    client-fingerprint: chrome
    uuid: *your-uuid*
    flow: xtls-rprx-vision
    reality-opts:
      public-key: *your-pbk*
      short-id: *your-shortid*

rule-providers:
  refilter-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/domain-rule.mrs
    path: ./rule-providers/refilter-domains.mrs
    interval: 86400

  cloudflare-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/cloudflare.mrs
    path: ./rule-providers/cloudflare-domains.mrs
    interval: 86400

  cloudflare-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/cloudflare.mrs
    path: ./rule-providers/cloudflare-ips.mrs
    interval: 86400

  category-ai:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ai-!cn.mrs
    path: ./rule-providers/category-ai.mrs

  discord:
    type: inline
    behavior: classical
    format: text
    payload:
      - AND,((DOMAIN-KEYWORD,discord),(NOT,((DOMAIN-SUFFIX,ru))))
      - AND,((RULE-SET,cloudflare-ips,no-resolve),(NETWORK,TCP),(DST-PORT,2000-2300/8443))
      - AND,((RULE-SET,cloudflare-ips,no-resolve),(NETWORK,UDP),(DST-PORT,19200-19400/50000-51000))
      - AND,((IP-CIDR,5.200.14.128/25,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,34.0.0.0/15,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,34.2.0.0/15,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,35.192.0.0/11,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,66.22.192.0/18,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,138.128.136.0/21,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))

  telegram-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/telegram.mrs
    path: ./rule-providers/telegram-domains.mrs
    interval: 86400

  telegram-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/telegram.mrs
    path: ./rule-providers/telegram-ips.mrs
    interval: 86400

  meta-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/facebook.mrs
    path: ./rule-providers/meta-domains.mrs
    interval: 86400

  meta-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/facebook.mrs
    path: ./rule-providers/meta-ips.mrs
    interval: 86400

  reddit:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/reddit.mrs
    path: ./rule-providers/reddit.mrs
    interval: 86400

  spotify:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/spotify.mrs
    path: ./rule-providers/spotify.mrs
    interval: 86400

  steam:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/steam.mrs
    path: ./rule-providers/steam.mrs
    interval: 86400

  twitch:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/twitch.mrs
    path: ./rule-providers/twitch.mrs
    interval: 86400

  twitter:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/twitter.mrs
    path: ./rule-providers/twitter.mrs
    interval: 86400

  youtube:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/youtube.mrs
    path: ./rule-providers/youtube.mrs
    interval: 86400

rules:
  - AND,((DST-PORT,443),(NETWORK,UDP)),QUIC
  - OR,((DOMAIN-SUFFIX,gql.twitch.tv),(DOMAIN-SUFFIX,usher.ttvnw.net)),–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã # –†–∞–∑–±–ª–æ–∫–∏—Ä–æ–≤–∫–∞ –≤—ã—Å–æ–∫–æ–≥–æ –∫–∞—á–µ—Å—Ç–≤–∞ –Ω–∞ Twitch.tv
  - RULE-SET,category-ai,AI
  - RULE-SET,steam,Steam
  - RULE-SET,spotify,Spotify
  - RULE-SET,reddit,Reddit
  - RULE-SET,youtube,YouTube
  - RULE-SET,twitch,Twitch
  - RULE-SET,twitter,Twitter
  - RULE-SET,discord,Discord
  - OR,((RULE-SET,meta-domains),(RULE-SET,meta-ips,no-resolve)),Meta
  - OR,((RULE-SET,telegram-domains),(RULE-SET,telegram-ips,no-resolve)),Telegram
  - OR,((RULE-SET,cloudflare-domains),(RULE-SET,cloudflare-ips)),Cloudflare
  - RULE-SET,refilter-domains,–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
  - MATCH,DIRECT
