#######################################################################################################
# –û–ø–∏—Å–∞–Ω–∏–µ:
# –í–µ–±-–∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å –¥–æ—Å—Ç—É–ø–µ–Ω –ø–æ –∞–¥—Ä–µ—Å—É http://192.168.1.1:9090/ui (–≤–º–µ—Å—Ç–æ 192.168.1.1 –º–æ–∂–µ—Ç –±—ã—Ç—å –ª—é–±–æ–π IP, –≥–¥–µ –∑–∞–ø—É—â–µ–Ω –¥–∞–Ω–Ω—ã–π –∫–æ–Ω—Ñ–∏–≥). –ü–æ—Å–ª–µ –¥–æ–±–∞–≤–ª–µ–Ω–∏—è —Å–µ—Ä–≤–µ—Ä–∞ –∏ –∑–∞–ø—É—Å–∫–∞ mihomo –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –∑–∞–π—Ç–∏ –≤ –≤–µ–±-–∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å –∏ –≤—ã–±—Ä–∞—Ç—å –Ω—É–∂–Ω–æ–µ –ø–æ–¥–∫–ª—é—á–µ–Ω–∏–µ –¥–ª—è –ø—Ä–æ–∫—Å–∏-–≥—Ä—É–ø–ø
# –ì—Ä—É–ø–ø–∞ "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã" —Å–æ–¥–µ—Ä–∂–∏—Ç —Å–ø–∏—Å–æ–∫ –¥–æ–º–µ–Ω–æ–≤ –±–æ–ª—å—à–∏–Ω—Å—Ç–≤–∞ –∑–∞–±–ª–æ–∫–∏—Ä–æ–≤–∞–Ω–Ω—ã—Ö —Ä–µ—Å—É—Ä—Å–æ–≤ (–∫–∞–∫ —Å–Ω–∞—Ä—É–∂–∏, —Ç–∞–∫ –∏ –≤–Ω—É—Ç—Ä–∏)
# –û—Å—Ç–∞–ª—å–Ω—ã–µ –≥—Ä—É–ø–ø—ã YouTube/Discord –∏ —Ç–¥ –∏–º–µ—é—Ç –ø—Ä–∏–æ—Ä–∏—Ç–µ—Ç –Ω–∞–¥ –≥—Ä—É–ø–ø–æ–π "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã". E—Å–ª–∏ –ø–µ—Ä–µ–æ–ø—Ä–µ–¥–µ–ª–µ–Ω–∏–µ –Ω–µ –Ω—É–∂–Ω–æ, –º–æ–∂–Ω–æ –≤—ã–±—Ä–∞—Ç—å "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã" –≤ –∫–∞—á–µ—Å—Ç–≤–µ –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è –∏ —É–ø—Ä–∞–≤–ª—è—Ç—å –≤—Å–µ–º–∏ –≥—Ä—É–ø–ø–∞–º–∏ —Ä–∞–∑–æ–º –≤ –≥—Ä—É–ø–ø–µ "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã"
#######################################################################################################
# –î–ª—è —Ä–∞–±–æ—Ç—ã Discord —Ç—Ä–µ–±—É–µ—Ç—Å—è –ø—Ä–æ–∫—Å–∏—Ä–æ–≤–∞—Ç—å –ø–æ—Ä—Ç—ã XKeen: 80,443,2000:2300,8443,19200:19400,50000:50030
# –î–ª—è —Ä–∞–±–æ—Ç—ã Whatsapp/Telegram —Ç—Ä–µ–±—É–µ—Ç—Å—è –ø—Ä–æ–∫—Å–∏—Ä–æ–≤–∞—Ç—å –ø–æ—Ä—Ç—ã Xkeen: 80,443,596:599,1400,3478,5222
#######################################################################################################

log-level: silent
allow-lan: true
redir-port: 5000
tproxy-port: 5001
ipv6: true
mode: rule
external-controller: 0.0.0.0:9090
external-ui: zashboard
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
profile: { store-selected: true }

sniffer:
  enable: true
  sniff:
    HTTP:
    TLS:
    QUIC:

anchors:
  a1: &domain { type: http, format: mrs, behavior: domain, interval: 86400 }
  a2: &ipcidr { type: http, format: mrs, behavior: ipcidr, interval: 86400 }
  a3: &classical { type: http, format: text, behavior: classical, interval: 86400 }
  a4: &inline { type: inline, behavior: classical }

#############################################################################################
# –ü—Ä–∏–º–µ—Ä VLESS –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è –ë–ï–ó –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è –ø–æ–¥–ø–∏—Å–∫–∏ (–†–ê–°–ö–û–ú–ú–ï–ù–¢–ò–†–û–í–ê–¢–¨ –î–õ–Ø –ò–°–ü–û–õ–¨–ó–û–í–ê–ù–ò–Ø) #
#############################################################################################
# proxies:
#   - name: vless-reality
#     type: vless
#     server: *your-server*
#     port: 443
#     network: tcp
#     udp: true
#     tls: true
#     packet-encoding: xudp
#     servername: *your-sni*
#     client-fingerprint: chrome
#     uuid: *your-uuid*
#     flow: xtls-rprx-vision
#     reality-opts:
#       public-key: *your-public-key*
#       short-id: *your-shortid*

######################################################################################
# –ü—Ä–∏–º–µ—Ä –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è –° –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ–º –ø–æ–¥–ø–∏—Å–∫–∏ (–†–ê–°–ö–û–ú–ú–ï–ù–¢–ò–†–û–í–ê–¢–¨ –î–õ–Ø –ò–°–ü–û–õ–¨–ó–û–í–ê–ù–ò–Ø) #
######################################################################################
# proxy-providers:
#   proxy-sub:
#     type: http
#     url: https://–í–ê–®–ê_–°–°–´–õ–ö–ê_–ù–ê_–ü–û–î–ü–ò–°–ö–£
#     path: ./proxy-providers/proxy-sub.yml
#     interval: 3600
#     health-check:
#       enable: true
#       url: https://www.gstatic.com/generate_204
#       interval: 300
#       timeout: 2000
#       lazy: false
#       expected-status: 204
#     override:
#       udp: true
#       tfo: true

proxy-groups:
  - name: –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Reject.png
    include-all: true

  - name: YouTube
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Discord
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Twitch
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    include-all: true
    proxies: [DIRECT, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Reddit
    type: select
    icon: https://www.redditstatic.com/shreddit/assets/favicon/192x192.png
    include-all: true
    proxies: [DIRECT, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Meta
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/meta.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Spotify
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    include-all: true
    exclude-filter: üá∑üá∫
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Telegram
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    include-all: true
    proxies: [DIRECT, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Steam
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    include-all: true
    proxies: [DIRECT, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Cloudflare
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    include-all: true
    proxies: [PASS, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: AI
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    include-all: true
    exclude-filter: üá∑üá∫
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Twitter
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: QUIC
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/quic.png
    proxies: [REJECT, PASS]

rule-providers:
  category-ai@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ai-!cn.mrs }
  cloudflare@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/cloudflare.mrs }
  cloudflare@ipcidr: { <<: *ipcidr, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/cloudflare.mrs }
  discord@classical: { <<: *classical, url: https://github.com/zxc-rv/assets/raw/main/rules/discord.list }
  meta@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/facebook.mrs }
  meta@ipcidr: { <<: *ipcidr, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/facebook.mrs }
  reddit@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/reddit.mrs }
  refilter@domain: { <<: *domain, url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/domain-rule.mrs }
  spotify@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/spotify.mrs }
  steam@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/steam.mrs }
  telegram@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/telegram.mrs }
  telegram@ipcidr: { <<: *ipcidr, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/telegram.mrs }
  twitch@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/twitch.mrs }
  twitter@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/twitter.mrs }
  youtube@domain: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/youtube.mrs }

rules:
  - AND,((DST-PORT,443),(NETWORK,UDP)),QUIC
  - OR,((DOMAIN-SUFFIX,gql.twitch.tv),(DOMAIN-SUFFIX,usher.ttvnw.net)),–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã # –†–∞–∑–±–ª–æ–∫–∏—Ä–æ–≤–∫–∞ –≤—ã—Å–æ–∫–æ–≥–æ –∫–∞—á–µ—Å—Ç–≤–∞ –Ω–∞ Twitch.tv
  - RULE-SET,category-ai@domain,AI
  - RULE-SET,steam@domain,Steam
  - RULE-SET,spotify@domain,Spotify
  - RULE-SET,reddit@domain,Reddit
  - RULE-SET,youtube@domain,YouTube
  - RULE-SET,twitch@domain,Twitch
  - RULE-SET,twitter@domain,Twitter
  - RULE-SET,discord@classical,Discord
  - OR,((RULE-SET,meta@domain),(RULE-SET,meta@ipcidr,no-resolve)),Meta
  - OR,((RULE-SET,telegram@domain),(RULE-SET,telegram@ipcidr,no-resolve)),Telegram
  - OR,((RULE-SET,cloudflare@domain),(RULE-SET,cloudflare@ipcidr)),Cloudflare
  - RULE-SET,refilter@domain,–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
  - MATCH,DIRECT
