#######################################################################################################
# –û–ø–∏—Å–∞–Ω–∏–µ:
# –ü–æ—Å–ª–µ –¥–æ–±–∞–≤–ª–µ–Ω–∏—è –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è –∏ –∑–∞–ø—É—Å–∫–∞ mihomo –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –∑–∞–π—Ç–∏ –≤ –≤–µ–±-–∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å –∏ –≤—ã–±—Ä–∞—Ç—å –Ω—É–∂–Ω–æ–µ –ø–æ–¥–∫–ª—é—á–µ–Ω–∏–µ –¥–ª—è —Å–µ–ª–µ–∫—Ç–æ—Ä–æ–≤.
# –ì—Ä—É–ø–ø–∞ "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã" —Å–æ–¥–µ—Ä–∂–∏—Ç —Å–ø–∏—Å–æ–∫ –¥–æ–º–µ–Ω–æ–≤ –±–æ–ª—å—à–∏–Ω—Å—Ç–≤–∞ –∑–∞–±–ª–æ–∫–∏—Ä–æ–≤–∞–Ω–Ω—ã—Ö —Ä–µ—Å—É—Ä—Å–æ–≤.
# –û—Å—Ç–∞–ª—å–Ω—ã–µ –≥—Ä—É–ø–ø—ã YouTube/Discord –∏ —Ç–¥ –∏–º–µ—é—Ç –ø—Ä–∏–æ—Ä–∏—Ç–µ—Ç –Ω–∞–¥ –≥—Ä—É–ø–ø–æ–π "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã". 
#######################################################################################################
# –î–ª—è —Ä–∞–±–æ—Ç—ã Discord —Ç—Ä–µ–±—É–µ—Ç—Å—è –ø—Ä–æ–∫—Å–∏—Ä–æ–≤–∞—Ç—å –ø–æ—Ä—Ç—ã XKeen: 80,443,2000:2300,8443,19200:19400,50000:50030
# –î–ª—è —Ä–∞–±–æ—Ç—ã Whatsapp/Telegram —Ç—Ä–µ–±—É–µ—Ç—Å—è –ø—Ä–æ–∫—Å–∏—Ä–æ–≤–∞—Ç—å –ø–æ—Ä—Ç—ã Xkeen: 80,443,596:599,1400,3478,5222
#######################################################################################################

log-level: silent
allow-lan: true
redir-port: 5000
tproxy-port: 5001
find-process-mode: off
unified-delay: true
external-controller: 0.0.0.0:9090
external-ui: zashboard
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
profile: { store-selected: true }

sniffer:
  enable: true
  sniff:
    HTTP:
    TLS:

anchors:
  a1: &domain { type: http, format: mrs, behavior: domain, interval: 86400 }
  a2: &ipcidr { type: http, format: mrs, behavior: ipcidr, interval: 86400 }
  a3: &classical { type: http, format: text, behavior: classical, interval: 86400 }
  a4: &inline { type: inline, behavior: classical }

proxy-groups:
  - name: –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Reject.png
    include-all: true

  - name: YouTube
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Discord
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Twitch
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    include-all: true
    proxies: [DIRECT, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Reddit
    type: select
    icon: https://www.redditstatic.com/shreddit/assets/favicon/192x192.png
    include-all: true
    proxies: [DIRECT, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Meta
    type: select
    icon: https://github.com/zxc-rv/assets/raw/main/group-icons/meta.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Spotify
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    include-all: true
    exclude-filter: üá∑üá∫
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Telegram
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

  - name: Steam
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    include-all: true
    proxies: [DIRECT, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: CDN
    type: select
    icon: https://www.svgrepo.com/show/396567/globe-with-meridians.svg
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, PASS]
  
  - name: Google
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    include-all: true
    proxies: [PASS, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: GitHub
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png
    include-all: true
    proxies: [PASS, –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: AI
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    include-all: true
    exclude-filter: üá∑üá∫
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã]

  - name: Twitter
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    include-all: true
    proxies: [–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã, DIRECT]

rule-providers:
  adlist@domain: { <<: *domain, url: https://github.com/zxc-rv/ad-filter/releases/latest/download/adlist.mrs }
  amazon@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/amazon.mrs }
  amazon@ipcidr: { <<: *ipcidr, url: https://github.com/PentiumB/CDN-RuleSet/releases/latest/download/amazon.mrs }
  akamai@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/akamai.mrs }
  akamai@ipcidr: { <<: *ipcidr, url: https://github.com/PentiumB/CDN-RuleSet/releases/latest/download/akamai.mrs }
  category-ai@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs }
  cloudflare@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cloudflare.mrs }
  cloudflare@ipcidr: { <<: *ipcidr, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cloudflare.mrs }
  digitalocean@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/digitalocean.mrs }
  digitalocean@ipcidr: { <<: *ipcidr, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/asn/AS14061.mrs }
  scaleway@ipcidr: { <<: *ipcidr, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/asn/AS12876.mrs }
  discord@classical: { <<: *classical, url: https://github.com/zxc-rv/assets/raw/main/rules/discord.list }
  fastly@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/fastly.mrs }
  fastly@ipcidr: { <<: *ipcidr, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/fastly.mrs }
  google@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs }
  google@ipcidr: { <<: *ipcidr, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs }
  github@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs }
  hetzner@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/hetzner.mrs }
  hetzner-1@ipcidr: { <<: *ipcidr, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/asn/AS24940.mrs }
  hetzner-2@ipcidr: { <<: *ipcidr, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/asn/AS212317.mrs }
  hetzner-3@ipcidr: { <<: *ipcidr, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/asn/AS213230.mrs }
  hetzner-4@ipcidr: { <<: *ipcidr, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/asn/AS215859.mrs }
  meta@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/meta.mrs }
  meta@ipcidr: { <<: *ipcidr, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.mrs }
  oracle@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/oracle.mrs }
  oracle@ipcidr: { <<: *ipcidr, url: https://github.com/PentiumB/CDN-RuleSet/releases/latest/download/oracle.mrs }
  reddit@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/reddit.mrs }
  refilter@domain: { <<: *domain, url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/domain-rule.mrs }
  spotify@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs }
  steam@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs }
  telegram@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs }
  telegram@ipcidr: { <<: *ipcidr, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs }
  twitch@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitch.mrs }
  twitter@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs }
  youtube@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs }
  user@classical: # –°–í–û–ò –ü–†–ê–í–ò–õ–ê
    type: inline
    behavior: classical
    payload: # –¢–∏–ø—ã –ø—Ä–∞–≤–∏–ª –∏ –ø—Ä–∏–º–µ—Ä—ã: https://wiki.metacubex.one/ru/config/rules/
      - DOMAIN-SUFFIX,2ip.io

rules:
  - RULE-SET,adlist@domain,REJECT # –ë–ª–æ–∫–∏—Ä–æ–≤–∫–∞ —Ä–µ–∫–ª–∞–º—ã
  - AND,((DST-PORT,443),(NETWORK,UDP)),REJECT # –ë–ª–æ–∫–∏—Ä–æ–≤–∫–∞ QUIC
  - OR,((DOMAIN-SUFFIX,gql.twitch.tv),(DOMAIN-SUFFIX,usher.ttvnw.net)),–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã # –†–∞–∑–±–ª–æ–∫–∏—Ä–æ–≤–∫–∞ –≤—ã—Å–æ–∫–æ–≥–æ –∫–∞—á–µ—Å—Ç–≤–∞ –Ω–∞ Twitch.tv (–º–æ–∂–µ—Ç –≤—ã–∑–≤–∞—Ç—å —Ä–µ–∫–ª–∞–º—É)
  - RULE-SET,category-ai@domain,AI
  - RULE-SET,steam@domain,Steam
  - RULE-SET,spotify@domain,Spotify
  - RULE-SET,reddit@domain,Reddit
  - RULE-SET,youtube@domain,YouTube
  - RULE-SET,twitch@domain,Twitch
  - RULE-SET,twitter@domain,Twitter
  - RULE-SET,discord@classical,Discord
  - OR,((RULE-SET,meta@domain),(RULE-SET,meta@ipcidr,no-resolve)),Meta
  - OR,((RULE-SET,telegram@domain),(RULE-SET,telegram@ipcidr,no-resolve)),Telegram
  - OR,((RULE-SET,refilter@domain),(RULE-SET,user@classical)),–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
  - RULE-SET,github@domain,GitHub
  - OR,((RULE-SET,google@domain),(RULE-SET,google@ipcidr)),Google
  - OR,((RULE-SET,amazon@domain),(RULE-SET,amazon@ipcidr)),CDN
  - OR,((RULE-SET,akamai@domain),(RULE-SET,akamai@ipcidr)),CDN
  - OR,((RULE-SET,cloudflare@domain),(RULE-SET,cloudflare@ipcidr)),CDN
  - OR,((RULE-SET,digitalocean@domain),(RULE-SET,digitalocean@ipcidr)),CDN
  - OR,((RULE-SET,fastly@domain),(RULE-SET,fastly@ipcidr)),CDN
  - OR,((RULE-SET,oracle@domain),(RULE-SET,oracle@ipcidr)),CDN
  - OR,((RULE-SET,hetzner@domain),(RULE-SET,hetzner-1@ipcidr),(RULE-SET,hetzner-2@ipcidr),(RULE-SET,hetzner-3@ipcidr),(RULE-SET,hetzner-4@ipcidr)),CDN
  - RULE-SET,scaleway@ipcidr,CDN
  - MATCH,DIRECT
